modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/TBoshoven/MinecraftMods/issues"
license="GPLv3"

[[mods]]
modId="magic_doorknob"
version="${file.jarVersion}"
displayName="Magic Doorknob"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-magic-doorknob"
logoFile="logo.png"
authors="Tom Boshoven"
description='''
A doorknob that does not require a door.
'''

[[dependencies.magic_doorknob]]
modId="neoforge"
type="required"
versionRange="[21.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.magic_doorknob]]
modId="minecraft"
type="required"
versionRange="[1.21.0,1.22)"
ordering="NONE"
side="BOTH"
