@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.tomboshoven.minecraft.magicmirror.reflection.modifiers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
