@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.tomboshoven.minecraft.magicdoorknob.modelloaders;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
