version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Copying build.gradle for caching
          command: cp build.gradle build.gradle.original
      - run:
          name: Updating build number
          # Library version is MC version followed by tag name (or "MASTER" or "DEV") and build number.
          command: |
            if [[ $CIRCLE_TAG ]]; then
              TAG_VERSION="$(echo "$CIRCLE_TAG" | sed -E 's/[^0-9]+//')"
              sed -Ei 's/^(\s*version = ")([0-9]+\.){2}[0-9]+-DEV\.0+"$/\1'$TAG_VERSION'.'$CIRCLE_BUILD_NUM'"/' build.gradle
            else
              [[ $CIRCLE_BRANCH = '1.14.4' ]] && LIB_VERSION=MASTER || LIB_VERSION=DEV
              sed -Ei 's/^(\s*version = "([0-9]+\.){2}[0-9]+-)DEV\.0+"$/\1'$LIB_VERSION'.'$CIRCLE_BUILD_NUM'"/' build.gradle
            fi
      - restore_cache:
          key: circleci-minecraft-mods-gradle-{{ checksum "build.gradle.original" }}
      - run:
          name: Data Generation
          command: |
            _JAVA_OPTIONS='-Xmx1G -Xms1G' ./gradlew runData
      - run:
          name: Building
          command: |
            if [[ $CIRCLE_TAG ]]; then
              TAG_BUILD="$(echo "$CIRCLE_TAG" | sed -E 's/-[0-9.-]+$//' | sed -E 's/(^|-)([^-])/\U\2/g')"
              ./gradlew build "$TAG_BUILD:build"
            else
              ./gradlew build
            fi
      - run:
          name: Collecting artifacts
          command: |
            mkdir -p build/libs
            cp */build/libs/*.jar build/libs
      - store_artifacts:
          path: build/libs
          destination: libs
      # Save the Gradle cache so we don't have to redownload things all the time
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-minecraft-mods-gradle-{{ checksum "build.gradle.original" }}
      - persist_to_workspace:
          root: build
          paths:
            - libs/*.jar
  release-github:
    docker:
      - image: gableroux/github-release:v1.0.2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Upload assets to GitHub
          command: |
            for f in /tmp/workspace/libs/*.jar; do
              github-release upload -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" -t "$CIRCLE_TAG" -n "$(basename "$f")" -f "$f" 2>/dev/null
            done

workflows:
  version: 2
  build:
    jobs:
      - build
  build-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - release-github:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          context: GitHub Release
