@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.tomboshoven.minecraft.magicdoorknob;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
