@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.tomboshoven.minecraft.magicdoorknob.enchantments;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
