@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.tomboshoven.minecraft.magicdoorknob.enchantments;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
