@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.tomboshoven.minecraft.magicdoorknob.modelloaders.textured;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
