modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/TBoshoven/MinecraftMods/issues"
license="GPLv3"

[[mods]]
modId="magic_mirror"
version="${file.jarVersion}"
displayName="Magic Mirror"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-magic-mirror"
logoFile="logo.png"
authors="Tom Boshoven"
description='''
A mirror that has magic properties.
It can be made to look like a skeleton, or you could even give it some armor and use it as a fancy armor stand.
'''
