@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.tomboshoven.minecraft.magicdoorknob.blocks.colorhandlers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
