package com.tomboshoven.minecraft.magicdoorknob.blocks;

import com.tomboshoven.minecraft.magicdoorknob.MagicDoorknobMod;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.PushReaction;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;

/**
 * Collection of all blocks in the mod.
 */
public final class Blocks {
    private static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(MagicDoorknobMod.MOD_ID);

    /**
     * The block properties shared between the magic door and doorway.
     */
    private static final BlockBehaviour.Properties DOORWAY_BLOCK_PROPERTIES = BlockBehaviour.Properties.of().pushReaction(PushReaction.BLOCK).noOcclusion();

    /**
     * A magic doorway block. Generated by a magic doorknob.
     */
    public static final Supplier<Block> MAGIC_DOORWAY =
            BLOCKS.registerBlock("magic_doorway", MagicDoorwayBlock::new, DOORWAY_BLOCK_PROPERTIES);

    /**
     * A magic door block. Generated by a magic doorknob and the entrance to a magic doorway.
     */
    public static final Supplier<Block> MAGIC_DOOR =
            BLOCKS.registerBlock("magic_door", MagicDoorBlock::new, DOORWAY_BLOCK_PROPERTIES);

    private Blocks() {
    }

    public static void register(IEventBus eventBus) {
        BLOCKS.register(eventBus);
    }
}
