package com.tomboshoven.minecraft.magicdoorknob.blocks;

import com.tomboshoven.minecraft.magicdoorknob.ModMagicDoorknob;
import mcp.MethodsReturnNonnullByDefault;
import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraftforge.event.RegistryEvent.Register;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.eventbus.api.SubscribeEvent;

import javax.annotation.ParametersAreNonnullByDefault;

/**
 * Collection of all blocks in the mod.
 */
@EventBusSubscriber
@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
public final class Blocks {
    /**
     * A magic doorway block. Generated by a magic doorknob.
     */
    public static final Block blockMagicDoorway = new BlockMagicDoorway()
            .setRegistryName(ModMagicDoorknob.MOD_ID, "magic_doorway")
            .setTranslationKey(String.format("%s.magic_doorway", ModMagicDoorknob.MOD_ID))
            .setCreativeTab(CreativeTabs.MISC);

    /**
     * A magic door block. Generated by a magic doorknob and the entrance to a magic doorway.
     */
    public static final Block blockMagicDoor = new BlockMagicDoor()
            .setRegistryName(ModMagicDoorknob.MOD_ID, "magic_door")
            .setTranslationKey(String.format("%s.magic_door", ModMagicDoorknob.MOD_ID))
            .setCreativeTab(CreativeTabs.MISC);

    private Blocks() {
    }

    @SuppressWarnings("BoundedWildcard")
    @SubscribeEvent
    public static void registerBlocks(Register<Block> event) {
        event.getRegistry().registerAll(blockMagicDoorway, blockMagicDoor);
    }
}
