@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.tomboshoven.minecraft.magicdoorknob.modeldata;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
