@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.tomboshoven.minecraft.magicmirror.reflection;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
