@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.tomboshoven.minecraft.magicdoorknob.client.clientextensions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
