# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '40 22 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 90
        days-before-issue-close: 14
        stale-issue-label: stale
        stale-issue-message: "This issue was marked stale because it has been open for 90 days with no activity."
        close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
        days-before-pr-stale: -1
        days-before-pr-close: -1
        any-of-issue-labels: needs-info
